development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  pool: 5
  timeout: 5000
  username: rails_dev
  password: '1234567890'

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  pool: 5
  timeout: 5000
  username: rails_dev
  password: '1234567890'

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  timeout: 5000
  username: rails_dev
  password: '1234567890'

